// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MaichessBotArenaService.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GlobalCapacitySchedulerFeature : object, Xunit.IClassFixture<GlobalCapacitySchedulerFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Global capacity scheduler", @"  The arena reconciles the whole set of collections against the single global
  concurrency cap: queued games start as soon as capacity frees, oldest
  collection first (FIFO), and never more than the cap run at once. Raising the
  limit fills the new headroom immediately; lowering it launches nothing and lets
  in-flight games drain.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CapacityScheduler.feature"
#line hidden
        
        public GlobalCapacitySchedulerFeature(GlobalCapacitySchedulerFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A collection created at full capacity starts when a running game finishes")]
        [Xunit.TraitAttribute("FeatureTitle", "Global capacity scheduler")]
        [Xunit.TraitAttribute("Description", "A collection created at full capacity starts when a running game finishes")]
        public async System.Threading.Tasks.Task ACollectionCreatedAtFullCapacityStartsWhenARunningGameFinishes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A collection created at full capacity starts when a running game finishes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("the known bots are \"a,b,c,d\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
    await testRunner.AndAsync("the concurrency limit is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table5.AddRow(new string[] {
                            "white",
                            "a"});
                table5.AddRow(new string[] {
                            "black",
                            "b"});
                table5.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
#line 11
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table5, "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table6.AddRow(new string[] {
                            "white",
                            "c"});
                table6.AddRow(new string[] {
                            "black",
                            "d"});
                table6.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
#line 16
    await testRunner.AndAsync("a setup is created:", ((string)(null)), table6, "And ");
#line hidden
#line 21
    await testRunner.ThenAsync("1 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
    await testRunner.AndAsync("1 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("setup 2 is \"pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.WhenAsync("one running game finishes as a white win", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("1 games are finished in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("1 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("0 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.AndAsync("setup 2 is \"running\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Queued collections start FIFO as capacity frees")]
        [Xunit.TraitAttribute("FeatureTitle", "Global capacity scheduler")]
        [Xunit.TraitAttribute("Description", "Queued collections start FIFO as capacity frees")]
        public async System.Threading.Tasks.Task QueuedCollectionsStartFIFOAsCapacityFrees()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Queued collections start FIFO as capacity frees", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("the known bots are \"a,b,c,d,e,f\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.AndAsync("the concurrency limit is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table7.AddRow(new string[] {
                            "white",
                            "a"});
                table7.AddRow(new string[] {
                            "black",
                            "b"});
                table7.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
#line 33
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table7, "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table8.AddRow(new string[] {
                            "white",
                            "c"});
                table8.AddRow(new string[] {
                            "black",
                            "d"});
                table8.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
#line 38
    await testRunner.AndAsync("a setup is created:", ((string)(null)), table8, "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table9.AddRow(new string[] {
                            "white",
                            "e"});
                table9.AddRow(new string[] {
                            "black",
                            "f"});
                table9.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
#line 43
    await testRunner.AndAsync("a setup is created:", ((string)(null)), table9, "And ");
#line hidden
#line 48
    await testRunner.ThenAsync("1 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
    await testRunner.AndAsync("2 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.WhenAsync("one running game finishes as a white win", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("setup 2 is \"running\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.AndAsync("setup 3 is \"pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.WhenAsync("one running game finishes as a white win", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
    await testRunner.ThenAsync("setup 3 is \"running\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Raising the limit immediately launches queued games up to the new cap")]
        [Xunit.TraitAttribute("FeatureTitle", "Global capacity scheduler")]
        [Xunit.TraitAttribute("Description", "Raising the limit immediately launches queued games up to the new cap")]
        public async System.Threading.Tasks.Task RaisingTheLimitImmediatelyLaunchesQueuedGamesUpToTheNewCap()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Raising the limit immediately launches queued games up to the new cap", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.AndAsync("the concurrency limit is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table10.AddRow(new string[] {
                            "white",
                            "a"});
                table10.AddRow(new string[] {
                            "black",
                            "b"});
                table10.AddRow(new string[] {
                            "games_per_fen",
                            "4"});
#line 59
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table10, "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("1 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 65
    await testRunner.AndAsync("3 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.WhenAsync("the concurrency limit is changed to 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("3 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
    await testRunner.AndAsync("1 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lowering the limit launches nothing and running drains to the cap")]
        [Xunit.TraitAttribute("FeatureTitle", "Global capacity scheduler")]
        [Xunit.TraitAttribute("Description", "Lowering the limit launches nothing and running drains to the cap")]
        public async System.Threading.Tasks.Task LoweringTheLimitLaunchesNothingAndRunningDrainsToTheCap()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lowering the limit launches nothing and running drains to the cap", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.AndAsync("the concurrency limit is 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table11.AddRow(new string[] {
                            "white",
                            "a"});
                table11.AddRow(new string[] {
                            "black",
                            "b"});
                table11.AddRow(new string[] {
                            "games_per_fen",
                            "4"});
#line 73
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table11, "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("4 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
    await testRunner.WhenAsync("the concurrency limit is changed to 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("4 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
    await testRunner.AndAsync("0 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.WhenAsync("one running game finishes as a white win", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("3 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
    await testRunner.AndAsync("0 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="An invalid limit change is rejected and launches nothing")]
        [Xunit.TraitAttribute("FeatureTitle", "Global capacity scheduler")]
        [Xunit.TraitAttribute("Description", "An invalid limit change is rejected and launches nothing")]
        public async System.Threading.Tasks.Task AnInvalidLimitChangeIsRejectedAndLaunchesNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An invalid limit change is rejected and launches nothing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.AndAsync("the concurrency limit is 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table12.AddRow(new string[] {
                            "white",
                            "a"});
                table12.AddRow(new string[] {
                            "black",
                            "b"});
                table12.AddRow(new string[] {
                            "games_per_fen",
                            "4"});
#line 89
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table12, "When ");
#line hidden
#line 94
    await testRunner.ThenAsync("2 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 95
    await testRunner.WhenAsync("the concurrency limit is changed to 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.ThenAsync("2 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
    await testRunner.AndAsync("2 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Several games finishing in one tick never launch past the cap")]
        [Xunit.TraitAttribute("FeatureTitle", "Global capacity scheduler")]
        [Xunit.TraitAttribute("Description", "Several games finishing in one tick never launch past the cap")]
        public async System.Threading.Tasks.Task SeveralGamesFinishingInOneTickNeverLaunchPastTheCap()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Several games finishing in one tick never launch past the cap", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
    await testRunner.AndAsync("the concurrency limit is 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table13.AddRow(new string[] {
                            "white",
                            "a"});
                table13.AddRow(new string[] {
                            "black",
                            "b"});
                table13.AddRow(new string[] {
                            "games_per_fen",
                            "9"});
#line 102
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table13, "When ");
#line hidden
#line 107
    await testRunner.ThenAsync("3 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
    await testRunner.AndAsync("6 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
    await testRunner.WhenAsync("all running games finish as a white win", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
    await testRunner.ThenAsync("3 games are running in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 111
    await testRunner.AndAsync("3 games are finished in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
    await testRunner.AndAsync("3 games are pending in total", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GlobalCapacitySchedulerFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GlobalCapacitySchedulerFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
