// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MaichessBotArenaService.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CollectionLifecycleFeature : object, Xunit.IClassFixture<CollectionLifecycleFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Collection lifecycle", ("  Creating a setup validates it, expands it into games, launches them under the\r\n" +
                "  global concurrency cap, advances as games finish, and finalizes."), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CollectionLifecycle.feature"
#line hidden
        
        public CollectionLifecycleFeature(CollectionLifecycleFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A blank name is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A blank name is rejected")]
        public async System.Threading.Tasks.Task ABlankNameIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A blank name is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table14.AddRow(new string[] {
                            "name",
                            ""});
                table14.AddRow(new string[] {
                            "white",
                            "a"});
                table14.AddRow(new string[] {
                            "black",
                            "b"});
#line 9
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table14, "When ");
#line hidden
#line 14
    await testRunner.ThenAsync("the create result is invalid input \"name is required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="An unknown time format is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "An unknown time format is rejected")]
        public async System.Threading.Tasks.Task AnUnknownTimeFormatIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown time format is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table15.AddRow(new string[] {
                            "white",
                            "a"});
                table15.AddRow(new string[] {
                            "black",
                            "b"});
                table15.AddRow(new string[] {
                            "time_format",
                            "99+99"});
#line 18
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table15, "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("the create result is invalid input \"unknown time_format_id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup without both bots is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup without both bots is rejected")]
        public async System.Threading.Tasks.Task ASingleSetupWithoutBothBotsIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup without both bots is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table16.AddRow(new string[] {
                            "white",
                            "a"});
                table16.AddRow(new string[] {
                            "black",
                            ""});
#line 27
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table16, "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the create result is invalid input \"white_bot_id and black_bot_id are required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup with an unknown bot is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup with an unknown bot is rejected")]
        public async System.Threading.Tasks.Task ASingleSetupWithAnUnknownBotIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup with an unknown bot is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table17.AddRow(new string[] {
                            "white",
                            "a"});
                table17.AddRow(new string[] {
                            "black",
                            "z"});
#line 35
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table17, "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("the create result is invalid input \"unknown bot_id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup with a blank white bot is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup with a blank white bot is rejected")]
        public async System.Threading.Tasks.Task ASingleSetupWithABlankWhiteBotIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup with a blank white bot is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 42
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table18.AddRow(new string[] {
                            "white",
                            ""});
                table18.AddRow(new string[] {
                            "black",
                            "b"});
#line 43
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table18, "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("the create result is invalid input \"white_bot_id and black_bot_id are required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup with an unknown white bot is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup with an unknown white bot is rejected")]
        public async System.Threading.Tasks.Task ASingleSetupWithAnUnknownWhiteBotIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup with an unknown white bot is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table19.AddRow(new string[] {
                            "white",
                            "z"});
                table19.AddRow(new string[] {
                            "black",
                            "b"});
#line 51
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table19, "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the create result is invalid input \"unknown bot_id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup with no games per FEN is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup with no games per FEN is rejected")]
        public async System.Threading.Tasks.Task ASingleSetupWithNoGamesPerFENIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup with no games per FEN is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table20.AddRow(new string[] {
                            "white",
                            "a"});
                table20.AddRow(new string[] {
                            "black",
                            "b"});
                table20.AddRow(new string[] {
                            "games_per_fen",
                            "0"});
#line 59
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table20, "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("the create result is invalid input \"games_per_fen must be at least 1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A matrix setup with fewer than two bots is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A matrix setup with fewer than two bots is rejected")]
        public async System.Threading.Tasks.Task AMatrixSetupWithFewerThanTwoBotsIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A matrix setup with fewer than two bots is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table21.AddRow(new string[] {
                            "kind",
                            "matrix"});
                table21.AddRow(new string[] {
                            "bots",
                            "a"});
#line 68
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table21, "When ");
#line hidden
#line 72
    await testRunner.ThenAsync("the create result is invalid input \"at least 2 bots are required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A matrix setup with an unknown bot is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A matrix setup with an unknown bot is rejected")]
        public async System.Threading.Tasks.Task AMatrixSetupWithAnUnknownBotIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A matrix setup with an unknown bot is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table22.AddRow(new string[] {
                            "kind",
                            "matrix"});
                table22.AddRow(new string[] {
                            "bots",
                            "a,z"});
#line 76
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table22, "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("the create result is invalid input \"unknown bot_id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A matrix setup with no games per FEN is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A matrix setup with no games per FEN is rejected")]
        public async System.Threading.Tasks.Task AMatrixSetupWithNoGamesPerFENIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A matrix setup with no games per FEN is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table23.AddRow(new string[] {
                            "kind",
                            "matrix"});
                table23.AddRow(new string[] {
                            "bots",
                            "a,b"});
                table23.AddRow(new string[] {
                            "games_per_fen",
                            "0"});
#line 84
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table23, "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("the create result is invalid input \"games_per_fen must be at least 1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A tournament setup with no FENs per stage is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A tournament setup with no FENs per stage is rejected")]
        public async System.Threading.Tasks.Task ATournamentSetupWithNoFENsPerStageIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tournament setup with no FENs per stage is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table24.AddRow(new string[] {
                            "kind",
                            "tournament"});
                table24.AddRow(new string[] {
                            "bots",
                            "a,b"});
                table24.AddRow(new string[] {
                            "fens_per_stage",
                            "0"});
#line 93
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table24, "When ");
#line hidden
#line 98
    await testRunner.ThenAsync("the create result is invalid input \"fens_per_stage must be at least 1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup launches its games and finishes")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup launches its games and finishes")]
        public async System.Threading.Tasks.Task ASingleSetupLaunchesItsGamesAndFinishes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup launches its games and finishes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table25.AddRow(new string[] {
                            "white",
                            "a"});
                table25.AddRow(new string[] {
                            "black",
                            "b"});
                table25.AddRow(new string[] {
                            "games_per_fen",
                            "4"});
                table25.AddRow(new string[] {
                            "switching",
                            "on"});
#line 104
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table25, "When ");
#line hidden
#line 110
    await testRunner.ThenAsync("the create result is success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 111
    await testRunner.AndAsync("the collection status is \"running\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
    await testRunner.AndAsync("4 games are running", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
    await testRunner.AndAsync("a game was launched with start_fen \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
    await testRunner.WhenAsync("the setup runs to completion with white always winning", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
    await testRunner.ThenAsync("the collection status is \"finished\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
    await testRunner.AndAsync("4 games are finished", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
    await testRunner.AndAsync("the collection has 4 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A single setup from a custom FEN launches with that start position")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A single setup from a custom FEN launches with that start position")]
        public async System.Threading.Tasks.Task ASingleSetupFromACustomFENLaunchesWithThatStartPosition()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A single setup from a custom FEN launches with that start position", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 120
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table26.AddRow(new string[] {
                            "white",
                            "a"});
                table26.AddRow(new string[] {
                            "black",
                            "b"});
                table26.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
                table26.AddRow(new string[] {
                            "fens",
                            "rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2"});
#line 121
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table26, "When ");
#line hidden
#line 127
    await testRunner.ThenAsync(("a game was launched with start_fen \"rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKB" +
                        "NR w KQkq c6 0 2\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A matrix setup plays every pair and finishes")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A matrix setup plays every pair and finishes")]
        public async System.Threading.Tasks.Task AMatrixSetupPlaysEveryPairAndFinishes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A matrix setup plays every pair and finishes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 131
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 132
    await testRunner.GivenAsync("the known bots are \"a,b,c\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table27.AddRow(new string[] {
                            "kind",
                            "matrix"});
                table27.AddRow(new string[] {
                            "bots",
                            "a,b,c"});
                table27.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
#line 133
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table27, "When ");
#line hidden
#line 138
    await testRunner.ThenAsync("the collection has 3 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 139
    await testRunner.WhenAsync("the setup runs to completion with white always winning", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
    await testRunner.ThenAsync("the collection status is \"finished\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 141
    await testRunner.AndAsync("3 games are finished", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A matrix setup in random-colors mode still plays every pair once per game")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A matrix setup in random-colors mode still plays every pair once per game")]
        public async System.Threading.Tasks.Task AMatrixSetupInRandom_ColorsModeStillPlaysEveryPairOncePerGame()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A matrix setup in random-colors mode still plays every pair once per game", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 144
    await testRunner.GivenAsync("the known bots are \"a,b,c\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table28.AddRow(new string[] {
                            "kind",
                            "matrix"});
                table28.AddRow(new string[] {
                            "bots",
                            "a,b,c"});
                table28.AddRow(new string[] {
                            "games_per_fen",
                            "1"});
                table28.AddRow(new string[] {
                            "matrix_mode",
                            "random"});
#line 145
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table28, "When ");
#line hidden
#line 151
    await testRunner.ThenAsync("the collection has 3 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 152
    await testRunner.WhenAsync("the setup runs to completion with white always winning", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
    await testRunner.ThenAsync("the collection status is \"finished\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 154
    await testRunner.AndAsync("3 games are finished", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A four-bot tournament runs through two rounds to a champion")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A four-bot tournament runs through two rounds to a champion")]
        public async System.Threading.Tasks.Task AFour_BotTournamentRunsThroughTwoRoundsToAChampion()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A four-bot tournament runs through two rounds to a champion", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 158
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 159
    await testRunner.GivenAsync("the known bots are \"a,b,c,d\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table29.AddRow(new string[] {
                            "kind",
                            "tournament"});
                table29.AddRow(new string[] {
                            "bots",
                            "a,b,c,d"});
                table29.AddRow(new string[] {
                            "fens_per_stage",
                            "1"});
#line 160
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table29, "When ");
#line hidden
#line 165
    await testRunner.ThenAsync("the collection has 4 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 166
    await testRunner.WhenAsync("the setup runs to completion with white always winning", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 167
    await testRunner.ThenAsync("the collection status is \"finished\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 168
    await testRunner.AndAsync("the collection winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
    await testRunner.AndAsync("the collection has 6 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A three-bot tournament gives the top seed a bye")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A three-bot tournament gives the top seed a bye")]
        public async System.Threading.Tasks.Task AThree_BotTournamentGivesTheTopSeedABye()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A three-bot tournament gives the top seed a bye", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 171
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 172
    await testRunner.GivenAsync("the known bots are \"a,b,c\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table30.AddRow(new string[] {
                            "kind",
                            "tournament"});
                table30.AddRow(new string[] {
                            "bots",
                            "a,b,c"});
                table30.AddRow(new string[] {
                            "fens_per_stage",
                            "1"});
#line 173
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table30, "When ");
#line hidden
#line 178
    await testRunner.ThenAsync("the collection has 2 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 179
    await testRunner.WhenAsync("the setup runs to completion with white always winning", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 180
    await testRunner.ThenAsync("the collection status is \"finished\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 181
    await testRunner.AndAsync("the collection winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A tournament in random-colors mode plays one game per stage")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A tournament in random-colors mode plays one game per stage")]
        public async System.Threading.Tasks.Task ATournamentInRandom_ColorsModePlaysOneGamePerStage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tournament in random-colors mode plays one game per stage", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 183
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 184
    await testRunner.GivenAsync("the known bots are \"a,b,c,d\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table31.AddRow(new string[] {
                            "kind",
                            "tournament"});
                table31.AddRow(new string[] {
                            "bots",
                            "a,b,c,d"});
                table31.AddRow(new string[] {
                            "fens_per_stage",
                            "1"});
                table31.AddRow(new string[] {
                            "mode",
                            "random"});
#line 185
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table31, "When ");
#line hidden
#line 191
    await testRunner.ThenAsync("the collection has 2 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 192
    await testRunner.WhenAsync("the setup runs to completion with white always winning", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 193
    await testRunner.ThenAsync("the collection winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 194
    await testRunner.AndAsync("the collection has 3 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The cap limits how many games of one setup run at once")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "The cap limits how many games of one setup run at once")]
        public async System.Threading.Tasks.Task TheCapLimitsHowManyGamesOfOneSetupRunAtOnce()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The cap limits how many games of one setup run at once", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 198
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 199
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 200
    await testRunner.AndAsync("the concurrency limit is 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table32.AddRow(new string[] {
                            "white",
                            "a"});
                table32.AddRow(new string[] {
                            "black",
                            "b"});
                table32.AddRow(new string[] {
                            "games_per_fen",
                            "6"});
#line 201
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table32, "When ");
#line hidden
#line 206
    await testRunner.ThenAsync("2 games are running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 207
    await testRunner.AndAsync("4 games are pending", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A new setup waits when the cap is already saturated")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "A new setup waits when the cap is already saturated")]
        public async System.Threading.Tasks.Task ANewSetupWaitsWhenTheCapIsAlreadySaturated()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A new setup waits when the cap is already saturated", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 209
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 210
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 211
    await testRunner.AndAsync("the concurrency limit is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table33.AddRow(new string[] {
                            "white",
                            "a"});
                table33.AddRow(new string[] {
                            "black",
                            "b"});
                table33.AddRow(new string[] {
                            "games_per_fen",
                            "2"});
#line 212
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table33, "When ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table34.AddRow(new string[] {
                            "white",
                            "a"});
                table34.AddRow(new string[] {
                            "black",
                            "b"});
                table34.AddRow(new string[] {
                            "games_per_fen",
                            "2"});
#line 217
    await testRunner.AndAsync("a setup is created:", ((string)(null)), table34, "And ");
#line hidden
#line 222
    await testRunner.ThenAsync("the collection status is \"pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 223
    await testRunner.AndAsync("0 games are running", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
    await testRunner.AndAsync("2 games are pending", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Collections can be listed and fetched")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "Collections can be listed and fetched")]
        public async System.Threading.Tasks.Task CollectionsCanBeListedAndFetched()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Collections can be listed and fetched", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 228
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 229
    await testRunner.GivenAsync("the known bots are \"a,b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "value"});
                table35.AddRow(new string[] {
                            "white",
                            "a"});
                table35.AddRow(new string[] {
                            "black",
                            "b"});
#line 230
    await testRunner.WhenAsync("a setup is created:", ((string)(null)), table35, "When ");
#line hidden
#line 234
    await testRunner.AndAsync("collections are listed with status \"\" limit 0 offset 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
    await testRunner.ThenAsync("1 collections are listed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 236
    await testRunner.WhenAsync("collections are listed with status \"running\" limit 5 offset 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 237
    await testRunner.ThenAsync("1 collections are listed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 238
    await testRunner.WhenAsync("the collection is fetched", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 239
    await testRunner.ThenAsync("the fetch returns the collection with its games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fetching a missing collection returns nothing")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "Fetching a missing collection returns nothing")]
        public async System.Threading.Tasks.Task FetchingAMissingCollectionReturnsNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fetching a missing collection returns nothing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 241
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 242
    await testRunner.WhenAsync("a missing collection \"nope\" is fetched", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 243
    await testRunner.ThenAsync("the fetch returns nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Finishing a game whose collection is gone is a no-op")]
        [Xunit.TraitAttribute("FeatureTitle", "Collection lifecycle")]
        [Xunit.TraitAttribute("Description", "Finishing a game whose collection is gone is a no-op")]
        public async System.Threading.Tasks.Task FinishingAGameWhoseCollectionIsGoneIsANo_Op()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Finishing a game whose collection is gone is a no-op", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 245
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 246
    await testRunner.WhenAsync("a finished game for a missing collection is handled", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 247
    await testRunner.ThenAsync("no games were launched", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CollectionLifecycleFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CollectionLifecycleFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
