// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MaichessBotArenaService.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SetupExpansionFeature : object, Xunit.IClassFixture<SetupExpansionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Setup expansion", "  The arena expands each setup config into the exact ordered list of games.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SetupExpansion.feature"
#line hidden
        
        public SetupExpansionFeature(SetupExpansionFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Single setup with fixed colors keeps the assignment for every game")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Single setup with fixed colors keeps the assignment for every game")]
        public async System.Threading.Tasks.Task SingleSetupWithFixedColorsKeepsTheAssignmentForEveryGame()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Single setup with fixed colors keeps the assignment for every game", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.WhenAsync(("a single setup expands white \"w\" black \"b\" over FENs \"standard\" with 3 games per " +
                        "FEN and color switching off"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table38.AddRow(new string[] {
                            "0",
                            "w",
                            "b",
                            "Standard"});
                table38.AddRow(new string[] {
                            "1",
                            "w",
                            "b",
                            "Standard"});
                table38.AddRow(new string[] {
                            "2",
                            "w",
                            "b",
                            "Standard"});
#line 6
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table38, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Single setup switching colors alternates every game")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Single setup switching colors alternates every game")]
        public async System.Threading.Tasks.Task SingleSetupSwitchingColorsAlternatesEveryGame()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Single setup switching colors alternates every game", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.WhenAsync(("a single setup expands white \"w\" black \"b\" over FENs \"standard\" with 4 games per " +
                        "FEN and color switching on"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table39.AddRow(new string[] {
                            "0",
                            "w",
                            "b",
                            "Standard"});
                table39.AddRow(new string[] {
                            "1",
                            "b",
                            "w",
                            "Standard"});
                table39.AddRow(new string[] {
                            "2",
                            "w",
                            "b",
                            "Standard"});
                table39.AddRow(new string[] {
                            "3",
                            "b",
                            "w",
                            "Standard"});
#line 14
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table39, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Single setup switching colors continues alternation across FENs")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Single setup switching colors continues alternation across FENs")]
        public async System.Threading.Tasks.Task SingleSetupSwitchingColorsContinuesAlternationAcrossFENs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Single setup switching colors continues alternation across FENs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.WhenAsync(("a single setup expands white \"w\" black \"b\" over FENs \"standard,posB\" with 1 games" +
                        " per FEN and color switching on"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table40.AddRow(new string[] {
                            "0",
                            "w",
                            "b",
                            "Standard"});
                table40.AddRow(new string[] {
                            "1",
                            "b",
                            "w",
                            "FEN 2"});
#line 23
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table40, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matrix setup plays every unordered pair once per FEN")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Matrix setup plays every unordered pair once per FEN")]
        public async System.Threading.Tasks.Task MatrixSetupPlaysEveryUnorderedPairOncePerFEN()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix setup plays every unordered pair once per FEN", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.WhenAsync(("a matrix setup expands bots \"a,b,c,d\" over FENs \"standard,posB\" with 1 games per " +
                        "FEN"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
    await testRunner.ThenAsync("the expansion has 12 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
    await testRunner.AndAsync("the expansion covers 6 distinct unordered pairs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matrix setup alternates colors per game within a pair")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Matrix setup alternates colors per game within a pair")]
        public async System.Threading.Tasks.Task MatrixSetupAlternatesColorsPerGameWithinAPair()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix setup alternates colors per game within a pair", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.WhenAsync("a matrix setup expands bots \"a,b\" over FENs \"standard\" with 2 games per FEN", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table41.AddRow(new string[] {
                            "0",
                            "a",
                            "b",
                            "Standard"});
                table41.AddRow(new string[] {
                            "1",
                            "b",
                            "a",
                            "Standard"});
#line 35
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table41, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matrix alternation continues across FENs within a pair")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Matrix alternation continues across FENs within a pair")]
        public async System.Threading.Tasks.Task MatrixAlternationContinuesAcrossFENsWithinAPair()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix alternation continues across FENs within a pair", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.WhenAsync("a matrix setup expands bots \"a,b\" over FENs \"standard,posB\" with 1 games per FEN", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table42.AddRow(new string[] {
                            "0",
                            "a",
                            "b",
                            "Standard"});
                table42.AddRow(new string[] {
                            "1",
                            "b",
                            "a",
                            "FEN 2"});
#line 42
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table42, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matrix random mode assigns each game\'s colors from the RNG")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Matrix random mode assigns each game\'s colors from the RNG")]
        public async System.Threading.Tasks.Task MatrixRandomModeAssignsEachGamesColorsFromTheRNG()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix random mode assigns each game\'s colors from the RNG", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.WhenAsync(("a matrix setup expands bots \"a,b\" over FENs \"standard\" with 3 games per FEN in ra" +
                        "ndom mode with RNG \"0,1,1\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table43.AddRow(new string[] {
                            "0",
                            "a",
                            "b",
                            "Standard"});
                table43.AddRow(new string[] {
                            "1",
                            "b",
                            "a",
                            "Standard"});
                table43.AddRow(new string[] {
                            "2",
                            "b",
                            "a",
                            "Standard"});
#line 49
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table43, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matrix random mode keeps games_per_fen as the game count")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Matrix random mode keeps games_per_fen as the game count")]
        public async System.Threading.Tasks.Task MatrixRandomModeKeepsGames_Per_FenAsTheGameCount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix random mode keeps games_per_fen as the game count", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
    await testRunner.WhenAsync(("a matrix setup expands bots \"a,b,c\" over FENs \"standard\" with 1 games per FEN in " +
                        "random mode with RNG \"0\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("the expansion has 3 games", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("the expansion covers 3 distinct unordered pairs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table44.AddRow(new string[] {
                            "0",
                            "a",
                            "b",
                            "Standard"});
                table44.AddRow(new string[] {
                            "1",
                            "a",
                            "c",
                            "Standard"});
                table44.AddRow(new string[] {
                            "2",
                            "b",
                            "c",
                            "Standard"});
#line 59
    await testRunner.AndAsync("the expansion produces:", ((string)(null)), table44, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tournament stage both-colors plays each FEN twice swapping colors")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Tournament stage both-colors plays each FEN twice swapping colors")]
        public async System.Threading.Tasks.Task TournamentStageBoth_ColorsPlaysEachFENTwiceSwappingColors()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tournament stage both-colors plays each FEN twice swapping colors", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 66
    await testRunner.WhenAsync(("a tournament stage expands bots \"a\" and \"b\" over FENs \"standard,posB\" in both-col" +
                        "ors mode"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table45.AddRow(new string[] {
                            "0",
                            "a",
                            "b",
                            "Standard"});
                table45.AddRow(new string[] {
                            "1",
                            "b",
                            "a",
                            "Standard"});
                table45.AddRow(new string[] {
                            "2",
                            "a",
                            "b",
                            "FEN 2"});
                table45.AddRow(new string[] {
                            "3",
                            "b",
                            "a",
                            "FEN 2"});
#line 67
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table45, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tournament stage random mode plays each FEN once using the RNG")]
        [Xunit.TraitAttribute("FeatureTitle", "Setup expansion")]
        [Xunit.TraitAttribute("Description", "Tournament stage random mode plays each FEN once using the RNG")]
        public async System.Threading.Tasks.Task TournamentStageRandomModePlaysEachFENOnceUsingTheRNG()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tournament stage random mode plays each FEN once using the RNG", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
    await testRunner.WhenAsync(("a tournament stage expands bots \"a\" and \"b\" over FENs \"standard,posB\" in random m" +
                        "ode with RNG \"0,1\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "order",
                            "white",
                            "black",
                            "label"});
                table46.AddRow(new string[] {
                            "0",
                            "a",
                            "b",
                            "Standard"});
                table46.AddRow(new string[] {
                            "1",
                            "b",
                            "a",
                            "FEN 2"});
#line 76
    await testRunner.ThenAsync("the expansion produces:", ((string)(null)), table46, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SetupExpansionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SetupExpansionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
