// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MaichessBotArenaService.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TournamentStageTie_BreakFeature : object, Xunit.IClassFixture<TournamentStageTie_BreakFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Tournament stage tie-break", ("  The stage winner is decided by the ladder: wins, then rounds-to-win, then\r\n  ag" +
                "gregate clock advantage, then aggregate material advantage, then a coin flip."), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TieBreak.feature"
#line hidden
        
        public TournamentStageTie_BreakFeature(TournamentStageTie_BreakFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="More wins wins the stage (bot a)")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "More wins wins the stage (bot a)")]
        public async System.Threading.Tasks.Task MoreWinsWinsTheStageBotA()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("More wins wins the stage (bot a)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome"});
                table38.AddRow(new string[] {
                            "a",
                            "b",
                            "white_won"});
                table38.AddRow(new string[] {
                            "a",
                            "b",
                            "white_won"});
                table38.AddRow(new string[] {
                            "b",
                            "a",
                            "white_won"});
#line 6
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table38, "Given ");
#line hidden
#line 11
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("the stage winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="More wins wins the stage (bot b)")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "More wins wins the stage (bot b)")]
        public async System.Threading.Tasks.Task MoreWinsWinsTheStageBotB()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("More wins wins the stage (bot b)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome"});
                table39.AddRow(new string[] {
                            "b",
                            "a",
                            "white_won"});
                table39.AddRow(new string[] {
                            "b",
                            "a",
                            "white_won"});
                table39.AddRow(new string[] {
                            "a",
                            "b",
                            "white_won"});
#line 15
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table39, "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("the stage winner is \"b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Equal wins, fewer rounds to win favours bot a")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "Equal wins, fewer rounds to win favours bot a")]
        public async System.Threading.Tasks.Task EqualWinsFewerRoundsToWinFavoursBotA()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Equal wins, fewer rounds to win favours bot a", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome"});
                table40.AddRow(new string[] {
                            "a",
                            "b",
                            "white_won"});
                table40.AddRow(new string[] {
                            "b",
                            "a",
                            "white_won"});
#line 24
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table40, "Given ");
#line hidden
#line 28
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("the stage winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Equal wins, fewer rounds to win favours bot b")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "Equal wins, fewer rounds to win favours bot b")]
        public async System.Threading.Tasks.Task EqualWinsFewerRoundsToWinFavoursBotB()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Equal wins, fewer rounds to win favours bot b", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome"});
                table41.AddRow(new string[] {
                            "b",
                            "a",
                            "white_won"});
                table41.AddRow(new string[] {
                            "a",
                            "b",
                            "white_won"});
#line 32
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table41, "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("the stage winner is \"b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="All draws, greater clock advantage favours bot a")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "All draws, greater clock advantage favours bot a")]
        public async System.Threading.Tasks.Task AllDrawsGreaterClockAdvantageFavoursBotA()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All draws, greater clock advantage favours bot a", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome",
                            "whiteMs",
                            "blackMs"});
                table42.AddRow(new string[] {
                            "a",
                            "b",
                            "draw",
                            "1000",
                            "500"});
#line 40
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table42, "Given ");
#line hidden
#line 43
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.ThenAsync("the stage winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="All draws, greater clock advantage favours bot b")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "All draws, greater clock advantage favours bot b")]
        public async System.Threading.Tasks.Task AllDrawsGreaterClockAdvantageFavoursBotB()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All draws, greater clock advantage favours bot b", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome",
                            "whiteMs",
                            "blackMs"});
                table43.AddRow(new string[] {
                            "a",
                            "b",
                            "draw",
                            "500",
                            "1000"});
#line 47
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table43, "Given ");
#line hidden
#line 50
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("the stage winner is \"b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Equal clocks, greater material favours bot a")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "Equal clocks, greater material favours bot a")]
        public async System.Threading.Tasks.Task EqualClocksGreaterMaterialFavoursBotA()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Equal clocks, greater material favours bot a", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome",
                            "whiteMs",
                            "blackMs",
                            "fen"});
                table44.AddRow(new string[] {
                            "a",
                            "b",
                            "draw",
                            "0",
                            "0",
                            "Q6k/8/8/8/8/8/8/K7 w - - 0 1"});
#line 54
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table44, "Given ");
#line hidden
#line 57
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the stage winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Equal clocks, greater material favours bot b")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "Equal clocks, greater material favours bot b")]
        public async System.Threading.Tasks.Task EqualClocksGreaterMaterialFavoursBotB()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Equal clocks, greater material favours bot b", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome",
                            "whiteMs",
                            "blackMs",
                            "fen"});
                table45.AddRow(new string[] {
                            "b",
                            "a",
                            "draw",
                            "0",
                            "0",
                            "Q6k/8/8/8/8/8/8/K7 w - - 0 1"});
#line 61
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table45, "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("the stage winner is \"b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Everything equal falls back to the coin flip (bot a)")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "Everything equal falls back to the coin flip (bot a)")]
        public async System.Threading.Tasks.Task EverythingEqualFallsBackToTheCoinFlipBotA()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Everything equal falls back to the coin flip (bot a)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome"});
                table46.AddRow(new string[] {
                            "a",
                            "b",
                            "draw"});
#line 68
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table46, "Given ");
#line hidden
#line 71
    await testRunner.AndAsync("the tie-break coin flip yields 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("the stage winner is \"a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Everything equal falls back to the coin flip (bot b)")]
        [Xunit.TraitAttribute("FeatureTitle", "Tournament stage tie-break")]
        [Xunit.TraitAttribute("Description", "Everything equal falls back to the coin flip (bot b)")]
        public async System.Threading.Tasks.Task EverythingEqualFallsBackToTheCoinFlipBotB()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Everything equal falls back to the coin flip (bot b)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "white",
                            "black",
                            "outcome"});
                table47.AddRow(new string[] {
                            "a",
                            "b",
                            "draw"});
#line 76
    await testRunner.GivenAsync("the stage games:", ((string)(null)), table47, "Given ");
#line hidden
#line 79
    await testRunner.AndAsync("the tie-break coin flip yields 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.WhenAsync("the stage winner is decided", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("the stage winner is \"b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TournamentStageTie_BreakFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TournamentStageTie_BreakFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
